namespace UnityEngine.PS4.IODevices
{
	public enum SceCameraFramerate
	{
		SCE_CAMERA_FRAMERATE_UNKNOWN = 0,
		SCE_CAMERA_FRAMERATE_7_5 = 7,
		SCE_CAMERA_FRAMERATE_15 = 15,
		SCE_CAMERA_FRAMERATE_30 = 30,
		SCE_CAMERA_FRAMERATE_60 = 60,
		SCE_CAMERA_FRAMERATE_120 = 120,
		SCE_CAMERA_FRAMERATE_240 = 240
	}
}
