namespace UnityEngine.PS4.IODevices
{
	public enum SceCameraConfigType
	{
		SCE_CAMERA_CONFIG_TYPE1 = 1,
		SCE_CAMERA_CONFIG_TYPE2 = 2,
		SCE_CAMERA_CONFIG_TYPE3 = 3,
		SCE_CAMERA_CONFIG_TYPE4 = 4,
		SCE_CAMERA_CONFIG_EXTENTION = 16
	}
}
