namespace UnityEngine.PS4.IODevices
{
	public enum SceCameraScaleFormat
	{
		SCE_CAMERA_SCALE_FORMAT_YUV422 = 0,
		SCE_CAMERA_SCALE_FORMAT_Y16 = 3,
		SCE_CAMERA_SCALE_FORMAT_Y8 = 4,
		SCE_CAMERA_SCALE_FORMAT_NO_USE = 16,
		SCE_CAMERA_SCALE_FORMAT_UNKNOWN = 255
	}
}
